name: Test
on:
  push: {}
  pull_request: {}
env:
  FORCE_COLOR: 2
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: bahmutov/npm-install@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: demo
      - run: npm run test
